#!/bin/sh

dir="$1"
: "${dir:=.}"

# make sort (and awk) behave programmatically:
LC_ALL=C
export LC_ALL

cd "$dir"
find . -name '*.ijs' -print | xargs awk '
/^[a-zA-Z][a-zA-Z0-9_]*[ 	]*=:/ {
	tag=$0; sub (/[ 	=].*/, "", tag)
	# Search pattern:
	# We simply match the identifier + copula at the line start.
	# The RHS is not included in the match.  If it were inlcuded,
	# any regex special characters would have to be quoted.  This
	# would be easy with a  gsub(/[][\\*.\/^$], "\\&", pattern).
	# We do not include that part though because it is good to be
	# a bit tolerant against code edits.
	# The perverted  "[=]" below to match a "=" is due to IRIX-5.3
	# nawk which would tokenize  /=:.*/ with an initial /= ("divide
	# by and assign").  Freaky.
	pattern=$0; sub (/[=]:.*/, "=:", pattern)
	printf ("%s\t%s\t/^%s/\n", tag, FILENAME, pattern)
}' | sort > tags
